title: Maximiliano
description: Personal website
gitlab_username: msandova
github_username: A6GibKm
email: contact@maximiliano.cc
url: "https://maximiliano.cc"

theme: theme
permalink: pretty
show_excerpts: true

author:
  name: Maximiliano
  email: contact@maximiliano.cc

md-theme:
  social_links:
    github: A6GibKm
    gitlab:
      - instance: gitlab.gnome.org
        username: msandova

sass:
  style: compressed

plugins:
  - jekyll-sitemap

markdown: kramdown

exclude:
  - vendor
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
  - package.json
  - theme.gemspec
  - theme
  - .nojekyll
