title: Deathwish
description: Personal blog
github_username: A6GibKm
email: contact@deathwish.info

markdown: kramdown
kramdown:
  math_engine: null

sass:
  style: compressed

excerpt_separator: <!-- more -->
permalink: pretty

exclude:
  - vendor
  - LICENCE
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
  - package.json
  - assets/tex
