title: Deathwish
description: Personal blog
github_username: A6GibKm
email: contact@deathwish.info

remote_theme: A6GibKm/deathwish-md-theme
permalink: pretty
# theme: deathwish-md-theme
show_excerpts: true

markdown: kramdown

author:
  name: deathwish
  email: contact@deathwish.info

md-theme:
  date_format: "%b %-d, %Y"
  # generate social links in footer
  social_links:
    # github:  A6GibKm
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

exclude:
  - vendor
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
  - package.json
