title: Deathwish
description: Personal blog
github_username: A6GibKm
email: contact@deathwish.info

remote_theme: A6GibKm/deathwish-md-theme
permalink: pretty
# theme: deathwish-md-theme
show_excerpts: true
# paginate: 5

markdown: kramdown

exclude:
  - vendor
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
  - package.json
