title: Deathwish
description: Personal blog
github_username: A6GibKm
email: contact@deathwish.info

remote_theme: https://github.com/A6GibKm/deathwish-md-theme

exclude:
  - vendor
  - LICENCE
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
  - package.json
