title: Deathwish
github_username: A6GibKm
email: contact@deathwish.info

permalink: pretty
theme: deathwish-md-theme
show_excerpts: true

markdown: kramdown

author:
  email: contact@deathwish.info

pluggins:
  - jekyll-time-to-read

exclude:
  - vendor
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
  - package.json
  - deathwish-md-theme.gemspec
