title: Deathwish
github_username: A6GibKm
email: contact@deathwish.info
description: >
  Ideas in maths, technology and programming.

permalink: pretty
theme: deathwish-md-theme
show_excerpts: true
sass:
  style: compressed

markdown: kramdown

author:
  name: M.
  email: contact@deathwish.info

url: "https://deathwish.info"

pluggins:
  - jekyll-sitemap # require after

exclude:
  - vendor
  - LICENSE
  - README.md
  # - CNAME Do not exclude
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
  - package.json
  - deathwish-md-theme.gemspec
  - deathwish-md-theme
  - .nojekyll
