name: Deplying site

on:
  push

jobs:
  jekyll:
    runs-on: ubuntu-16.04
    steps:

    - uses: actions/checkout@v2

    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    # Specify the Jekyll source location as a parameter
    - name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git clone https://github.com/A6GibKm/deathwish-md-theme.git src/deathwish-md-theme

    - uses: helaili/jekyll-action@2.0.3
      with:
        jekyll_src: src
      env:
        JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
